//
// Created by Niv Swisa on 09/01/2021.
//

#ifndef FINALPROJECT_SNAKEGAME_SNAKEGAMEINTERFACE_H
#define FINALPROJECT_SNAKEGAME_SNAKEGAMEINTERFACE_H


class SnakeGameInterface {

};


#endif //FINALPROJECT_SNAKEGAME_SNAKEGAMEINTERFACE_H
